import { StockTicker } from "../models/stock-tickers.model";

const allStockTickersList: StockTicker[] = [
  {symbol: "AAPL", name: "Apple Inc."},
  {symbol: "MSFT", name: "Microsoft Corporation"},
  {symbol: "AMZN", name: "Amazon.com Inc."},
  {symbol: "GOOGL", name: "Alphabet Inc. (Google)"},
  {symbol: "FB", name: "Meta Platforms Inc. (Facebook)"},
  {symbol: "TSLA", name: "Tesla Inc."},
  {symbol: "NVDA", name: "NVIDIA Corporation"},
  {symbol: "PYPL", name: "PayPal Holdings Inc."},
  {symbol: "NFLX", name: "Netflix Inc."},
  {symbol: "INTC", name: "Intel Corporation"},
  {symbol: "AMD", name: "Advanced Micro Devices Inc."},
  {symbol: "CSCO", name: "Cisco Systems Inc."},
  {symbol: "ADBE", name: "Adobe Inc."},
  {symbol: "NVDA", name: "NVIDIA Corporation"},
  {symbol: "CRM", name: "Salesforce.com Inc."},
  {symbol: "ORCL", name: "Oracle Corporation"},
  {symbol: "IBM", name: "International Business Machines Corporation"},
  {symbol: "AAPL", name: "Apple Inc."},
  {symbol: "INTC", name: "Intel Corporation"},
  {symbol: "TXN", name: "Texas Instruments Incorporated"},
  {symbol: "QCOM", name: "Qualcomm Incorporated"},
  {symbol: "V", name: "Visa Inc."},
  {symbol: "MA", name: "Mastercard Incorporated"},
  {symbol: "DIS", name: "The Walt Disney Company"},
  {symbol: "CMCSA", name: "Comcast Corporation"},
  {symbol: "PEP", name: "PepsiCo Inc."},
  {symbol: "KO", name: "The Coca-Cola Company"},
  {symbol: "NKE", name: "Nike Inc."},
  {symbol: "MCD", name: "McDonald's Corporation"},
  {symbol: "SBUX", name: "Starbucks Corporation"},
  {symbol: "WMT", name: "Walmart Inc."},
  {symbol: "HD", name: "The Home Depot Inc."},
  {symbol: "LOW", name: "Lowe's Companies Inc."},
  {symbol: "TGT", name: "Target Corporation"},
  {symbol: "COST", name: "Costco Wholesale Corporation"},
  {symbol: "CVS", name: "CVS Health Corporation"},
  {symbol: "WBA", name: "Walgreens Boots Alliance Inc."},
  {symbol: "UNH", name: "UnitedHealth Group Incorporated"},
  {symbol: "ANTM", name: "Anthem Inc."},
  {symbol: "CI", name: "Cigna Corporation"},
  {symbol: "AET", name: "Aetna Inc."},
  {symbol: "CVS", name: "CVS Health Corporation"},
  {symbol: "UNH", name: "UnitedHealth Group Incorporated"},
  {symbol: "ANTM", name: "Anthem Inc."},
  {symbol: "CI", name: "Cigna Corporation"},
  {symbol: "AET", name: "Aetna Inc."},
  {symbol: "CVS", name: "CVS Health Corporation"},
  {symbol: "UNH", name: "UnitedHealth Group Incorporated"},
  {symbol: "ANTM", name: "Anthem Inc."},
  {symbol: "CI", name: "Cigna Corporation"},
  {symbol: "AET", name: "Aetna Inc."},
  {symbol: "LMT", name: "Lockheed Martin Corporation"},
  {symbol: "RTX", name: "Raytheon Technologies Corporation"},
  {symbol: "BA", name: "The Boeing Company"},
  {symbol: "NOC", name: "Northrop Grumman Corporation"},
  {symbol: "GD", name: "General Dynamics Corporation"},
  {symbol: "LMT", name: "Lockheed Martin Corporation"},
  {symbol: "RTX", name: "Raytheon Technologies Corporation"},
  {symbol: "BA", name: "The Boeing Company"},
  {symbol: "NOC", name: "Northrop Grumman Corporation"},
  {symbol: "GD", name: "General Dynamics Corporation"},
  {symbol: "LMT", name: "Lockheed Martin Corporation"},
  {symbol: "RTX", name: "Raytheon Technologies Corporation"},
  {symbol: "BA", name: "The Boeing Company"},
  {symbol: "NOC", name: "Northrop Grumman Corporation"},
  {symbol: "GD", name: "General Dynamics Corporation"},
  {symbol: "LMT", name: "Lockheed Martin Corporation"},
  {symbol: "RTX", name: "Raytheon Technologies Corporation"},
  {symbol: "BA", name: "The Boeing Company"},
  {symbol: "NOC", name: "Northrop Grumman Corporation"},
  {symbol: "GD", name: "General Dynamics Corporation"},
  {symbol: "XOM", name: "Exxon Mobil Corporation"},
  {symbol: "CVX", name: "Chevron Corporation"},
  {symbol: "BP", name: "BP p.l.c."},
  {symbol: "TOT", name: "TotalEnergies SE"},
  {symbol: "RDS-A", name: "Royal Dutch Shell plc"},
  {symbol: "RDS-B", name: "Royal Dutch Shell plc"},
  {symbol: "PTR", name: "PetroChina Company Limited"},
  {symbol: "BP", name: "BP p.l.c."},
  {symbol: "TOT", name: "TotalEnergies SE"},
  {symbol: "RDS-A", name: "Royal Dutch Shell plc"},
  {symbol: "RDS-B", name: "Royal Dutch Shell plc"},
  {symbol: "PTR", name: "PetroChina Company Limited"}
]

export default allStockTickersList;
